# Generated by Django 4.0.6 on 2023-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0008_cname_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cname',
            name='secret_code',
            field=models.CharField(default='Secret Code', max_length=30),
        ),
    ]
