# Generated by Django 4.0.6 on 2023-04-28 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment_info', '0011_submissions_checked_by_submissions_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
