# Generated by Django 4.0.3 on 2023-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_info', '0013_alter_submissions_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_marks',
            field=models.IntegerField(default=10),
        ),
    ]
